[build]
  command = """
    pnpm install && \
    cd core && pnpm build && cd .. && \
    cd preview && pnpm build
  """
  publish = "preview/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 