[build]
  command = "pnpm install && cd core && pnpm build && cd .. && cd static-preview && pnpm build"
  publish = "static-preview/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/roster/*"
  to = "/roster/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 